# Generated by Django 3.2.3 on 2022-05-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPages', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='taught_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainPages.teacher'),
        ),
    ]
